myproject/myapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.prehome, name='prehome'),
    path('create_problem/', views.create_problem, name='create_problem'),
    path('home/', views.problem_list, name='problem_list'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/', views.profile_view, name='profile'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myproject/myapp/models.py
from django.contrib.auth.models import Group, User
from django.db import models

assigned_group = models.ForeignKey(Group, null=True, on_delete=models.SET_NULL)
resolved_group = models.ForeignKey(Group, null=True, on_delete=models.SET_NULL)

class Problem(models.Model):
    assigned_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='assigned_problems')
    resolved_user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name='resolved_problems')
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.CharField(max_length=15)
    description = models.TextField()
    priority_choices = [
        ('low', 'Низкий'),
        ('medium', 'Средний'),
        ('high', 'Высокий'),
    ]
    priority = models.CharField(max_length=10, choices=priority_choices)
    resolved_problems = [
        ('resolved', 'решено'),
        ('not resolved', 'не решено'),
    ]
    resolved = models.CharField(max_length=20, choices=resolved_problems, default='none')
    created_at = models.DateTimeField(auto_now_add=True)  # Поле даты создания

    def __str__(self):
        return self.name

myproject/myapp/forms.py
from django import forms
from django.contrib.auth.models import User  # Импортируйте модель User

from .models import Problem


class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['name', 'phone', 'email', 'description', 'priority', 'resolved', 'assigned_user']

    def __init__(self, *args, **kwargs):
        super(ProblemForm, self).__init__(*args, **kwargs)
        self.fields['assigned_user'].queryset = User.objects.filter(groups__name='Reception')

myproject/myapp/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from .forms import ProblemForm
from .models import Problem


def prehome(request):
    return render(request, "prehome/prehome.html", {"prehome": prehome})


def create_problem(request):
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            reception_group = Group.objects.get(name='Reception')
            reception_users = reception_group.user_set.all()
            if reception_users.exists():
                problem.assigned_user = reception_users[0] 
            problem.save()
            return redirect('problem_list')
    else:
        form = ProblemForm()
    return render(request, 'create_problem.html', {'form': form})
    

def problem_list(request):
    user = request.user
    if user.groups.filter(name='Reception').exists():
        problems = Problem.objects.all()
    else:
        problems = Problem.objects.filter(assigned_user=user)
    
    return render(request, 'problem_list.html', {'problems': problems, 'is_tester': user.groups.filter(name='Tester').exists()})

def update_problem_status(problem, new_status, user):
    if new_status == 'resolved':
        problem.resolved_user = problem.assigned_user
        tester_group = Group.objects.get(name='Tester')
        testers = tester_group.user_set.all()
        if testers.exists():
            problem.assigned_user = testers[0]  
    problem.resolved = new_status
    problem.save()

def profile_view(request):
    user = request.user
    is_tester = user.groups.filter(name='Tester').exists()
    return render(request, 'login\profile.html', {'user': user, 'is_tester': is_tester})

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('problem_list')
        else:
            return render(request, 'login\login.html', {'error_message': 'Invalid login'})
    else:
        return render(request, 'login\login.html')

def logout_view(request):
    logout(request)
    return redirect('prehome')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'login\signup.html'

myproject/templates/create_problem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>    
    {% block content %}
      <h2>Создать проблему</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
      </form>
    {% endblock %}
</body>
</html>

myproject/templates/login/login.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>
</head>
<body>
  {% if error_message %}
  <p class="error-message">{{ error_message }}</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" name="username" id="username" required>
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" name="password" id="password" required>
    </div>
    <input type="submit" value="Log in" class="btn">
  </form>
</body>
</html>

myproject/templates/login/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>profile</title>
</head>
<body>
    <h1>Welcome {{ user.username }}!</h1>
    <p class="email">Email: {{ user.email }}</p>
    <p><a class="btn" href="{% url 'logout' %}">Logout</a></p>
    <p><a href="home\home_after_login.html"></a></p>    
</body>
</html>

myproject/templates/login/signup.html
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>signup</title>
</head>
<body>
  <form method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign up" class="btn">

    <a href="{% url 'prehome' %}" class="back">Назад</a>

  </form>


</body>
</html>

myproject/templates/prehome/prehome.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>some label</title>
</head>
<body>
    <div class="home">
        <h1>Чтобы подолжить, необходимо войти в систему</h1>
        <a href="{% url 'signup' %}" class="btn">Регистация</a>
        <a href="{% url 'login' %}" class="btn">Вход</a>
    </div>
</body>
</html>

myproject/templates/problem_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        {% block content %}
        {% csrf_token %}
      <button><a class="btn" href="{% url 'profile' %}">Профиль</a></button>

      <h2>Список проблем</h2>
      <table>
        <thead>
          <tr>
            <th>Имя</th>
            <th>Телефон</th>
            <th>Емэйл</th>
            <th>Описание</th>
            <th>Приоритет</th>
            <th>Решено</th>
            <th>Дата создания</th>
          </tr>
        </thead>
        <tbody>
          {% for problem in problems %}
            <tr>
              <td>{{ problem.name }}</td>
              <td>{{ problem.phone }}</td>
              <td>{{ problem.email }}</td>
              <td>{{ problem.description }}</td>
              <td>{{ problem.get_priority_display }}</td>
              <td>{{ problem.get_resolved_display }}</td>
              <td>{{ problem.created_at }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <button><a class="btn" href="{% url 'create_problem' %}">Создать проблему</a></button>

    {% endblock %}
</body>
</html>